[package]
name = "media_org"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
audiotags = "0.4.1"
clap = { version = "4.2.1", features = ["derive", "env"] }
regex = "1.7.3"
